// TYPES FILE

export const types = {
    // TAB
    SET_TRADE_MODAL_VISIBILITY: 'SET_TRADE_MODAL_VISIBILITY',
    // MARKET
    GET_HOLDINGS_BEGIN: 'GET_HOLDINGS_BEGIN',
    GET_HOLDINGS_SUCCESS: 'GET_HOLDINGS_SUCCESS',
    GET_HOLDINGS_FAILURE: 'GET_HOLDINGS_FAILURE',
    GET_COIN_MARKET_BEGIN: 'GET_COIN_MARKET_BEGIN',
    GET_COIN_MARKET_SUCCESS: 'GET_COIN_MARKET_SUCCESS',
    GET_COIN_MARKET_FAILURE: 'GET_COIN_MARKET_FAILURE',
}